#ifndef __WLAUDIO_H_
#define __WLAUDIO_H_

#include <QString>

static QString wl6Sounds[88] =
{
    "HITWALLSND", "SELECTWPNSND", "SELECTITEMSND", "HEARTBEATSND", "MOVEGUN2SND",            // 0  - 4
    "MOVEGUN1SND", "NOWAYSND", "NAZIHITPLAYERSND", "SCHABBSTHROWSND", "PLAYERDEATHSND",      // 5  - 9
    "DOGDEATHSND", "ATKGATLINGSND", "GETKEYSND", "NOITEMSND", "WALK1SND",                    // 10 - 14
    "WALK2SND", "TAKEDAMAGESND", "GAMEOVERSND", "OPENDOORSND", "CLOSEDOORSND",               // 15 - 19
    "DONOTHINGSND", "HALTSND", "DEATHSCREAM2SND", "ATKKNIFESND", "ATKPISTOLSND",             // 20 - 24
    "DEATHSCREAM3SND", "ATKMACHINEGUNSND", "HITENEMYSND", "SHOOTDOORSND", "DEATHSCREAM1SND", // 25 - 29
    "GETMACHINESND", "GETAMMOSND", "SHOOTSND", "HEALTH1SND", "HEALTH2SND",                   // 30 - 34
    "BONUS1SND", "BONUS2SND", "BONUS3SND", "GETGATLINGSND", "ESCPRESSEDSND",                 // 35 - 39
    "LEVELDONESND", "DOGBARKSND", "ENDBONUS1SND", "ENDBONUS2SND", "BONUS1UPSND",             // 40 - 44
    "BONUS4SND", "PUSHWALLSND", "NOBONUSSND", "PERCENT100SND", "BOSSACTIVESND",              // 45 - 49
    "MUTTISND", "SCHUTZADSND", "AHHHGSND", "DIESND", "EVASND",                               // 50 - 54
    "GUTENTAGSND", "LEBENSND", "SCHEISTSND", "NAZIFIRESND", "BOSSFIRESND",                   // 55 - 59
    "SSFIRESND", "SLURPIESND", "TOT_HUNDSND", "MEINGOTTSND", "SCHABBSHASND",                 // 60 - 64
    "HITLERHASND", "SPIONSND", "NEINSOVASSND", "DOGATTACKSND", "FLAMETHROWERSND",            // 65 - 69
    "MECHSTEPSND", "GOOBSSND", "YEAHSND", "DEATHSCREAM4SND", "DEATHSCREAM5SND",              // 70 - 74
    "DEATHSCREAM6SND", "DEATHSCREAM7SND", "DEATHSCREAM8SND", "DEATHSCREAM9SND", "DONNERSND", // 75 - 79
    "EINESND", "ERLAUBENSND", "KEINSND", "MEINSND", "ROSESND",                               // 80 - 84
    "MISSILEFIRESND", "MISSILEHITSND", "LASTSOUND"                                           // 85 - 87                                                                         // 160 - 161
};

static QString sodSounds[82] =
{
    "HITWALLSND", "MISSILEHITSND", "SELECTITEMSND", "GHOSTSIGHTSND", "MOVEGUN2SND",          // 0  - 4
    "MOVEGUN1SND", "NOWAYSND", "NAZIHITPLAYERSND", "MISSILEFIRESND", "PLAYERDEATHSND",       // 5  - 9
    "DOGDEATHSND", "ATKGATLINGSND", "GETKEYSND", "NOITEMSND", "WALK1SND",                    // 10 - 14
    "WALK2SND", "TAKEDAMAGESND", "GAMEOVERSND", "OPENDOORSND", "CLOSEDOORSND",               // 15 - 19
    "DONOTHINGSND", "HALTSND", "DEATHSCREAM2SND", "ATKKNIFESND", "ATKPISTOLSND",             // 20 - 24
    "DEATHSCREAM3SND", "ATKMACHINEGUNSND", "HITENEMYSND", "SHOOTDOORSND", "DEATHSCREAM1SND", // 25 - 29
    "GETMACHINESND", "GETAMMOSND", "SHOOTSND", "HEALTH1SND", "HEALTH2SND",                   // 30 - 34
    "BONUS1SND", "BONUS2SND", "BONUS3SND", "GETGATLINGSND", "ESCPRESSEDSND",                 // 35 - 39
    "LEVELDONESND", "DOGBARKSND", "ENDBONUS1SND", "ENDBONUS2SND", "BONUS1UPSND",             // 40 - 44
    "BONUS4SND", "PUSHWALLSND", "NOBONUSSND", "PERCENT100SND", "BOSSACTIVESND",              // 45 - 49
    "DEATHSCREAM4SND", "SCHUTZADSND", "AHHHGSND", "DEATHSCREAM5SND", "DEATHSCREAM7SND",      // 50 - 54
    "DEATHSCREAM8SND", "LEBENSND", "DEATHSCREAM6SND", "NAZIFIRESND", "BOSSFIRESND",          // 55 - 59
    "SSFIRESND", "SLURPIESND", "GHOSTFADESND", "DEATHSCREAM9SND", "GETAMMOBOXSND",           // 60 - 64
    "ANGELSIGHTSND", "SPIONSND", "NEINSOVASSND", "DOGATTACKSND", "ANGELFIRESND",             // 65 - 69
    "TRANSSIGHTSND", "TRANSDEATHSND", "WILHELMSIGHTSND", "WILHELMSIGHTSND", "UBERDEATHSND",  // 70 - 74
    "KNIGHTSIGHTSND", "KNIGHTDEATHSND", "ANGELDEATHSND", "KNIGHTMISSILESND", "GETSPEARSND",  // 75 - 79
    "ANGELTIREDSND", "LASTSOUND"                                                             // 80 - 81                                                                         // 160 - 161
};

static QString wl6Music[28] =
{
    "CORNER_MUS", "DUNGEON_MUS", "WARMARCH_MUS", "GETTHEM_MUS", "HEADACHE_MUS",      // 0  - 4
    "HITLWLTZ_MUS", "INTROCW3_MUS", "NAZI_NOR_MUS", "NAZI_OMI_MUS", "POW_MUS",       // 5  - 9
    "SALUTE_MUS", "SEARCHN_MUS", "SUSPENSE_MUS", "VICTORS_MUS", "WONDERIN_MUS",      // 10 - 14
    "FUNKYOU_MUS", "ENDLEVEL_MUS", "GOINGAFT_MUS", "PREGNANT_MUS", "ULTIMATE_MUS",   // 15 - 19
    "NAZI_RAP_MUS", "ZEROHOUR_MUS", "TWELFTH_MUS", "ROSTER_MUS", "URAHERO_MUS",      // 20 - 24
    "VICMARCH_MUS", "PACMAN_MUS", "LASTMUSIC"                                        // 25 - 27
};

static QString sodMusic[25] =
{
    "XFUNKIE_MUS", "DUNGEON_MUS", "XDEATH_MUS", "GETTHEM_MUS", "XTIPTOE_MUS",        // 0  - 4
    "GOINGAFT_MUS", "URAHERO_MUS", "XTHEEND_MUS", "NAZI_OMI_MUS", "POW_MUS",         // 5  - 9
    "TWELFTH_MUS", "SEARCHN_MUS", "SUSPENSE_MUS", "ZEROHOUR_MUS", "WONDERIN_MUS",    // 10 - 14
    "ULTIMATE_MUS", "ENDLEVEL_MUS", "XEVIL_MUS", "XJAZNAZI_MUS", "COPYPRO_MUS",      // 15 - 19
    "XAWARD_MUS", "XPUTIT_MUS", "XGETYOU_MUS", "XTOWER2_MUS", "LASTMUSIC"            // 20 - 24
};

#endif
